Midbay-NG/Controllers/AdminController.cs
using Midbay_NG.MyModels;
using Midbay_NG.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace Midbay_NG.Controllers
{

    public class AdminController : Controller
    {
        public GalleryRepository repo;
        public ProjectRepository prepo;
        public ServiceRepository srepo;
        public ConsultantRepository crepo;
        public AdminController()
        {
            repo = new GalleryRepository();
            prepo = new ProjectRepository();
            srepo = new ServiceRepository();
            crepo = new ConsultantRepository();
        }
       
        public ActionResult Gallery()
        {
            var x = repo.GetGallery;
            return View(repo.GetGallery);
        }
        public ActionResult AddGallery()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddGallery(Gallery gallery, HttpPostedFileBase image)
        {
            if(image !=null)
            {
                string documentname =  Guid.NewGuid().ToString() + image.FileName.Substring(image.FileName.Count() - 4);
                string filename = repo.path+ "\\"+ documentname ;
                if(!Directory.Exists(repo.path))
                {
                    Directory.CreateDirectory(repo.path);
                }
                image.SaveAs(filename);
                gallery.image = filename;
                gallery.filename = documentname;
                

            }
            gallery.date = DateTime.Now;
            repo.AddGallery(gallery);
            return RedirectToAction("Gallery");
        }

        public ActionResult DeleteGallery(int Id)
        {
            repo.DeleteGallery(Id);
            return RedirectToAction("Gallery");
        }
        public ActionResult EditGallery(int Id)
        {
            return View(repo.GetGallery.Where(p=>p.Id == Id).SingleOrDefault());
        }
        [HttpPost]
        public ActionResult EditGallery(Gallery gallery, HttpPostedFileBase image)
        {
            if (image != null)
            { 

                string documentname = "\\" + Guid.NewGuid().ToString() + image.FileName.Substring(image.FileName.Length - 4);
                string filename = repo.path + documentname;
                if (!Directory.Exists(repo.path))
                {
                    Directory.CreateDirectory(repo.path);
                }
                image.SaveAs(filename);
                gallery.image = filename;
                gallery.filename = documentname;


            }
            gallery.date = DateTime.Now;
            repo.EditGallery(gallery);
            return RedirectToAction("Gallery");
        }

        public ActionResult Projects()
        {
            
            return View(prepo.GetProjects);
        }

        public ActionResult AddProject()
        {
           ViewBag.categories= prepo.GetCategories();
            return View();
        }
        [HttpPost]
        public ActionResult AddProject(Project project,IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid && files !=null)
            {
                var compressed = repo.CompressedPath;
                var path = repo.ProjectImages;

              
                    project.Images = prepo.SaveProjectImage(files, path, compressed);
                //prepo.CompressImage(repo.CompressedPath, project.Images);
                
                prepo.AddProject(project);
               
                TempData["status"] = "Success";
            }
            else
            {
                ViewBag.categories = prepo.GetCategories();
                ModelState.AddModelError(string.Empty, "Error");
                return View(project);
            }

            return RedirectToAction("Projects");
        }
        public ActionResult EditProject(int Id)
        {
            ViewBag.categories = prepo.GetCategories();
            return View(prepo.GetProject(Id));
        }
        [HttpPost]
        public ActionResult EditProject(Project project, IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                string images = prepo.GetProject(project.Id).Images;
                var compressed = repo.CompressedPath;
                var path = repo.ProjectImages;


                project.Images = prepo.EditProjectImage(files, path, images);
                //prepo.CompressImage(repo.CompressedPath, project.Images);

                prepo.EditProject(project);

                TempData["status"] = "Success";
            }
            else
            {
                ViewBag.categories = prepo.GetCategories();
                ModelState.AddModelError(string.Empty,"Error");
                return View(prepo.GetProject(project.Id));
            }

            return RedirectToAction("Projects");
        }
        public ActionResult DeleteProject(int Id)
        {
            prepo.DeleteProject(Id);
            return RedirectToAction("Projects");
        }
        [Authorize]
        public ActionResult Services()
        {
            var x = Request.IsAuthenticated;
            return View(srepo.GetServices());
        }
        public ActionResult AddService()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddService(Service ser)
        {
            if(ModelState.IsValid)
            {
                srepo.AddService(ser);
                return RedirectToAction("Services");
            }
            else
            {
                return View(ser);
            }
           
        }
        public ActionResult EditService(int Id)
        {
            return View(srepo.GetService(Id));
        }
        [HttpPost]
        public ActionResult EditService(Service ser)
        {
            if (ModelState.IsValid)
            {
                srepo.EditService(ser);
                return RedirectToAction("Services");
            }
            else
            {
                return View(ser);
            }

        }
        public ActionResult DeleteService(int Id)
        {
            srepo.DeleteService(Id);
            return RedirectToAction("Services");
        }

        //consultants

        public ActionResult Consultants()
        {
            return View(crepo.GetConsultants());
        }
        public ActionResult AddConsultant()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddConsultant(Consultant ser, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if(image !=null)
                ser.Image =  crepo.SaveImage(image);
                crepo.AddConsultant(ser);
                return RedirectToAction("Consultants");
            }
            else
            {
                return View(ser);
            }

        }
        public ActionResult EditConsultant(int Id)
        {
            return View(crepo.GetConsultant(Id));
        }
        [HttpPost]
        public ActionResult EditConsultant(Consultant ser,HttpPostedFileBase imageE)
        {
            if (ModelState.IsValid)
            {
                if (imageE != null)
                     ser.Image = crepo.SaveImage(imageE);
                crepo.EditConsultant(ser);
                return RedirectToAction("Consultants");
            }
            else
            {
                return View(ser);
            }

        }
        public ActionResult DeleteConsultant(int Id)
        {
            crepo.DeleteConsultant(Id);
            return RedirectToAction("Consultants");
        }
        public ActionResult DeletePI(string image, int Id)
        {
            prepo.DeleteDBI(image, Id);
           
             
          
            return PartialView();
        }
        


    }
}

Midbay-NG/Controllers/ContentController.cs
using Midbay_NG.MyModels;
using Midbay_NG.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Midbay_NG.Controllers
{
    public class ContentController : Controller
    {
        public GalleryRepository repo;
        public ProjectRepository prepo;
        public ServiceRepository srepo;
        public ConsultantRepository crepo;
        public AimRepository arepo;
        public ContentController()
        {
            repo = new GalleryRepository();
            prepo = new ProjectRepository();
            srepo = new ServiceRepository();
            crepo = new ConsultantRepository();
            arepo = new AimRepository();
        }
        public ActionResult Aims()
        {
            return View(arepo.GetAims());
        }
        public ActionResult AddAim()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAim(Aim aim)
        {
            if(ModelState.IsValid)
            {
                arepo.AddAim(aim);
                return RedirectToAction("Aims");
            }
            ModelState.AddModelError(string.Empty, "Error");
            return View(aim);
        }
        public ActionResult EditAim(int Id)
        {
           
            return View(arepo.GetAim(Id));
        }
        [HttpPost]
        public ActionResult EditAim(Aim aim)
        {

            if (ModelState.IsValid)
            {
                arepo.EditAIm(aim);
                return RedirectToAction("Aims");
            }
            ModelState.AddModelError(string.Empty, "Error");
            return View(aim);
        }
        public ActionResult DeleteAim(int Id)
        {
            arepo.DeleteAim(Id);
            return RedirectToAction("Aims");
        }


    }
}

Midbay-NG/Views/Shared/Imager.cshtml
<div id='content'>
    <h1>Guillotine demo</h1>
    <div class='frame'>
        <img id='sample_picture' src='http://lorempixel.com/640/480/city'>
    </div>
    <div id='controls'>
        <button id='rotate_left' type='button' title='Rotate left'> &lt; </button>
        <button id='zoom_out' type='button' title='Zoom out'> - </button>
        <button id='fit' type='button' title='Fit image'> [ ]  </button>
        <button id='zoom_in' type='button' title='Zoom in'> + </button>
        <button id='rotate_right' type='button' title='Rotate right'> &gt; </button>
    </div>
    <ul id='data'>
        <div class='column'>
            <li>x: <span id='x'></span></li>
            <li>y: <span id='y'></span></li>
        </div>
        <div class='column'>
            <li>width:  <span id='w'></span></li>
            <li>height: <span id='h'></span></li>
        </div>
        <div class='column'>
            <li>scale: <span id='scale'></span></li>
            <li>angle: <span id='angle'></span></li>
        </div>
    </ul>
</div>
<script src='http://code.jquery.com/jquery-1.11.0.min.js'></script>
<script src='../js/jquery.guillotine.js'></script>
<script type='text/javascript'>
    jQuery(function() {
      var picture = $('#sample_picture');

      // Make sure the image is completely loaded before calling the plugin
      picture.one('load', function(){
        // Initialize plugin (with custom event)
        picture.guillotine({eventOnChange: 'guillotinechange'});

        // Display inital data
        var data = picture.guillotine('getData');
        for(var key in data) { $('#'+key).html(data[key]); }

        // Bind button actions
        $('#rotate_left').click(function(){ picture.guillotine('rotateLeft'); });
        $('#rotate_right').click(function(){ picture.guillotine('rotateRight'); });
        $('#fit').click(function(){ picture.guillotine('fit'); });
        $('#zoom_in').click(function(){ picture.guillotine('zoomIn'); });
        $('#zoom_out').click(function(){ picture.guillotine('zoomOut'); });

        // Update data on change
        picture.on('guillotinechange', function(ev, data, action) {
          data.scale = parseFloat(data.scale.toFixed(4));
          for(var k in data) { $('#'+k).html(data[k]); }
        });
      });

      // Make sure the 'load' event is triggered at least once (for cached images)
      if (picture.prop('complete')) picture.trigger('load')
    });
</script>

Midbay-NG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="reset">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Nigeria Limited</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/MyScripts/jquery.easing.1.3.js"></script>
    <script src="~/MyScripts/modernizr.2.5.3.min.js"></script>
    <link href="~/MyStyles/css.css" rel="stylesheet" />
    <script src="~/MyScripts/ImageUpload.js"></script>
    <script src="~/MyScripts/MyScript.js"></script>
    <script src="~/MyScripts/3dEffect.js"></script>
</head>
<body class="reset">
    <div class="head1">
        <div class="container">
            <div class="pull-left">
                @*<img src="~/Images/banner.png" />*@
                <img class="pull-left" src="~/Images/Midbay-logo.png" height="100" />
                <div class="motto visible-lg"><h4>We Engineer a habitat for humanity</h4></div>
            </div>
            <div class= "pull-right" id="listhead">
                <ul class="banner-content pull-right">
                    <li><a href=@Url.Action("Index")>HOME</a></li>
                    <li><a href=@Url.Action("About")>ABOUT</a></li>

                    <li><a href=@Url.Action("Gallery")>GALLERY</a></li>
                  <li><a href=@Url.Action("Gallery","Admin")>Admin</a></li>
                    <li><a href=@Url.Action("Contact")>CONTACT</a></li>
                  
                    <li><a href=@Url.Action("Affiliates")>AFFILIATIONS</a></li>
                </ul>
            </div>
           <div id="navcont"class="pull-right" >
               <button class="pull-right" id="toggler">
                    <i class="fa fa-bars"></i>
               </button>
               <div id="navlist">
                   <i class="fa fa-close"></i>
                   <ul class="nav nav-pills nav-justified" role="tablist">
                       <li><a href=@Url.Action("Index")>HOME</a></li>
                       <li><a href=@Url.Action("About")>ABOUT</a></li>

                       <li><a href=@Url.Action("Gallery")>GALLERY</a></li>
                       <li><a href=@Url.Action("Gallery","Admin")>Admin</a></li>
                       <li><a href=@Url.Action("Contact")>CONTACT</a></li>

                       <li><a href=@Url.Action("Affiliates")>AFFILIATIONS</a></li>
                   </ul>
               </div>
           </div>
        </div>

    </div>
    
    <div class="side1" style="margin-top:100px;">
        @RenderBody()
       
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>
    <div class="row side1 reset">
       <div class="container" style="padding:0">
           <div class="col-md-4 reset">
               <div class="footer1" style="border:none">
                   <div class="footer-content">
                       <h4>
                           FOR ORDER AND INQUIRIES PLEASE CALL:
                         
                       </h4><hr />

                       <h3><img src="~/Images/09.call.png" width="90" height="90" />
                       <b style="font-weight:bold"> 080-388-94389</b>
                       </h3>
                      
                       <h4>
                           OR EMAIL US AT:
                          
                       </h4>
                       <h4><img src="~/Images/E-mail.png" width="90" height="90" />&nbsp;
                       <b style="font-weight:bold"> engrsaf184@gmail.com</b>
                       </h4>
                   </div>
                  
               </div>

           </div>
           <div class="col-md-4 reset">
               <div class="footer1">
                   <div class="footer-content">
                       <h4 class="text-center">
                          LINKS

                       </h4><hr />
                       <img class="pull-left" src="~/Images/10.wireless.png" />
                           <ul class="footer-list pull-left">
                               <li><a href="#">HOME</a></li>
                               <li><a href="#">ABOUT</a></li>
                               <li><a href="#">GALLERY</a></li>
                               <li><a href="#">CONTACT</a></li>
                           </ul>                                                                  
                   </div>
                            
                   <div id="social" style="margin-left:40px; margin-top:20px; float:left;">
                     
                       <img style="margin-left:0;" src="~/Images/Facebook.png" />
                       <img src="~/Images/GooglePlus.png" />
                       <img src="~/Images/Twitter.png" />
                   </div>
               </div>
           </div>
           <div class="col-md-4 reset">
               <div class="footer1">
                   <div class="footer-content">
                       <h4 class="text-center">
                           Comments from our clients
                       </h4><hr />                 
                       <ul class="footer-list pull-left">
                           <li><a href="#">MID-BAY is a startup, but one that promises to acheive great things</a></li>
                           <li><a href="#">They are flexible and quite affordable</a></li>
                           <li><a href="#">Experienced and inspirational</a></li>
                           <li><a href="#">They get the task done</a></li>
                       </ul>
                   </div>
               </div>
           </div>
       </div>

    </div>
   
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Midbay-NG/Views/Shared/_adminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/MyStyles/css.css" rel="stylesheet" />
    <script src="~/MyScripts/admin.js"></script>
    <link href="~/MyStyles/admin.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/MyScripts/ImageUpload.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggle-sidebar collapsed">
                    MENU
                </button>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    Administrator
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <form class="navbar-form navbar-left" method="GET" role="search">
                    <div class="form-group">
                        <input type="text" name="q" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href=@Url.Action("Index","Home") target="_blank">Visit Site</a></li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Account
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="dropdown-header">SETTINGS</li>
                            <li class=""><a href="#">Other Link</a></li>
                            <li class=""><a href="#">Other Link</a></li>
                            <li class=""><a href="#">Other Link</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>  	<div class="container-fluid main-container">
        <div class="col-md-2 sidebar">
            <div class="row">
                <!-- uncomment code for absolute positioning tweek see top comment in css -->
                <div class="absolute-wrapper"> </div>
                <!-- Menu -->
                <div class="side-menu">
                    <nav class="navbar navbar-default" role="navigation">
                        <!-- Main Menu -->
                        <div class="side-menu-container">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="#"><span class="glyphicon glyphicon-dashboard"></span> Dashboard</a></li>
                                <li><a href=@Url.Action("Gallery","Admin")><span class="glyphicon glyphicon-plane"></span> Gallery</a></li>
                                <li><a href=@Url.Action("Projects","Admin")><span class="glyphicon glyphicon-plane"></span> Projects</a></li>
                                <li><a href=@Url.Action("Services","Admin")><span class="glyphicon glyphicon-cloud"></span> Services</a></li>
                                <li><a href=@Url.Action("Consultants","Admin")><span class="glyphicon glyphicon-cloud"></span> Consultants</a></li>
                                <li><a href=@Url.Action("Aims","Content")><span class="glyphicon glyphicon-cloud"></span> AIms</a></li>

                                <!-- Dropdown-->
                                <li class="panel panel-default" id="dropdown">
                                    <a data-toggle="collapse" href="#dropdown-lvl1">
                                        <span class="glyphicon glyphicon-user"></span> Sub Level <span class="caret"></span>
                                    </a>

                                    <!-- Dropdown level 1 -->
                                    <div id="dropdown-lvl1" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <ul class="nav navbar-nav">
                                                <li><a href=@Url.Action("AddProject","Admin")>Add Project</a></li>
                                                <li><a href=@Url.Action("Projects","Admin")>View Projects</a></li>
                                                <li><a href="#">Link</a></li>

                                                <!-- Dropdown level 2 -->
                                                <li class="panel panel-default" id="dropdown">
                                                    <a data-toggle="collapse" href="#dropdown-lvl2">
                                                        <span class="glyphicon glyphicon-off"></span> Sub Level <span class="caret"></span>
                                                    </a>
                                                    <div id="dropdown-lvl2" class="panel-collapse collapse">
                                                        <div class="panel-body">
                                                            <ul class="nav navbar-nav">
                                                                <li><a href="#">Link</a></li>
                                                                <li><a href="#">Link</a></li>
                                                                <li><a href="#">Link</a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </li>

                                <li><a href="#"><span class="glyphicon glyphicon-signal"></span> Link</a></li>

                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>

                </div>
            </div>
        </div>
        <div class="col-md-10 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Dashboard
                </div>
                <div class="panel-body">
                   @RenderBody();
                </div>
            </div>
        </div>
        <footer class="pull-left footer">
            <p class="col-md-12">
                <hr class="divider">
                Copyright &COPY; 2015 <a href="http://www.pingpong-labs.com">Gravitano</a>
            </p>
        </footer>
    </div>
 
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>